import 'dart:math';

/// How many cells a puzzle starts with.
///
/// Givens alone do not fully determine difficulty, but they are the honest
/// lever available to a generator that guarantees a unique solution — and the
/// bands below are the conventional ones.
enum SudokuDifficulty {
  easy('Easy', 45),
  medium('Medium', 36),
  hard('Hard', 30),
  expert('Expert', 26);

  const SudokuDifficulty(this.label, this.givens);

  final String label;
  final int givens;

  /// Finishing a harder grid is worth more.
  int get scoreBase => switch (this) {
    SudokuDifficulty.easy => 200,
    SudokuDifficulty.medium => 400,
    SudokuDifficulty.hard => 700,
    SudokuDifficulty.expert => 1100,
  };

  static SudokuDifficulty fromName(String? name) => SudokuDifficulty.values
      .firstWhere((d) => d.name == name, orElse: () => SudokuDifficulty.medium);
}

/// A generated 9×9 puzzle: the clues, and the one solution they admit.
class SudokuPuzzle {
  const SudokuPuzzle({
    required this.givens,
    required this.solution,
    required this.difficulty,
  });

  /// 81 cells, row-major. 0 means empty.
  final List<int> givens;

  /// The unique solution. Every generated puzzle has exactly one.
  final List<int> solution;

  final SudokuDifficulty difficulty;

  bool isGiven(int index) => givens[index] != 0;

  Map<String, dynamic> toJson() => {
    'givens': givens,
    'solution': solution,
    'difficulty': difficulty.name,
  };

  factory SudokuPuzzle.fromJson(Map<String, dynamic> json) => SudokuPuzzle(
    givens: (json['givens'] as List<dynamic>).cast<int>(),
    solution: (json['solution'] as List<dynamic>).cast<int>(),
    difficulty: SudokuDifficulty.fromName(json['difficulty'] as String?),
  );
}

/// Generates and solves 9×9 Sudoku.
///
/// Every puzzle is generated by filling a complete grid, then removing clues
/// one at a time and putting any back whose removal would leave more than one
/// solution. That uniqueness check is what separates a Sudoku from a grid of
/// numbers: a puzzle with two solutions cannot be reasoned to an answer, only
/// guessed at.
///
/// The search tracks used digits as bitmasks per row, column and box rather
/// than rescanning the grid for every candidate. That is what makes generation
/// fast enough to run on the device while the user waits — the scanning
/// version took minutes on the hardest band, and could not tell a contradictory
/// grid from a merely difficult one without exploring the whole space.
abstract final class Sudoku {
  static const size = 9;
  static const cells = 81;

  /// Bits 1–9 set: every digit, none of them "0".
  static const _all = 0x3FE;

  static int row(int index) => index ~/ size;
  static int col(int index) => index % size;
  static int box(int index) => (row(index) ~/ 3) * 3 + col(index) ~/ 3;

  static int _bits(int n) {
    var count = 0;
    while (n != 0) {
      n &= n - 1;
      count++;
    }
    return count;
  }

  /// Whether [value] may go in [index] given the rest of [grid].
  static bool canPlace(List<int> grid, int index, int value) {
    final r = row(index);
    final c = col(index);
    final boxRow = (r ~/ 3) * 3;
    final boxCol = (c ~/ 3) * 3;

    for (var i = 0; i < size; i++) {
      if (grid[r * size + i] == value) return false;
      if (grid[i * size + c] == value) return false;
      final b = (boxRow + i ~/ 3) * size + boxCol + i % 3;
      if (grid[b] == value) return false;
    }
    return true;
  }

  /// Builds the three mask tables, or returns null when [grid] already
  /// contradicts itself — which is how an impossible puzzle is rejected up
  /// front instead of by exhausting the search space.
  static _Masks? _masksFor(List<int> grid) {
    final rows = List.filled(size, 0);
    final cols = List.filled(size, 0);
    final boxes = List.filled(size, 0);

    for (var i = 0; i < cells; i++) {
      final value = grid[i];
      if (value == 0) continue;

      final bit = 1 << value;
      final r = row(i);
      final c = col(i);
      final b = box(i);

      if (rows[r] & bit != 0 || cols[c] & bit != 0 || boxes[b] & bit != 0) {
        return null;
      }
      rows[r] |= bit;
      cols[c] |= bit;
      boxes[b] |= bit;
    }
    return _Masks(rows, cols, boxes);
  }

  /// Counts solutions, stopping at [cap].
  ///
  /// Capped because the only question ever asked is "is this exactly one?",
  /// and an under-constrained grid can have millions.
  static int countSolutions(List<int> grid, {int cap = 2}) {
    final masks = _masksFor(grid);
    if (masks == null) return 0;

    final work = [...grid];
    var found = 0;

    bool search() {
      final index = _mostConstrained(work, masks);
      if (index == -1) {
        found++;
        return found >= cap;
      }

      var candidates = masks.candidatesAt(index);
      while (candidates != 0) {
        final bit = candidates & -candidates;
        candidates ^= bit;
        final value = bit.bitLength - 1;

        masks.place(index, value);
        work[index] = value;
        if (search()) {
          masks.remove(index, value);
          work[index] = 0;
          return true;
        }
        masks.remove(index, value);
        work[index] = 0;
      }
      return false;
    }

    search();
    return found;
  }

  /// The empty cell with the fewest candidates, or -1 when the grid is full.
  ///
  /// Solving from the most constrained cell rather than the first empty one is
  /// what keeps generation fast: a cell with one candidate is forced, and a
  /// cell with none prunes the branch immediately.
  static int _mostConstrained(List<int> grid, _Masks masks) {
    var best = -1;
    var bestCount = size + 1;

    for (var i = 0; i < cells; i++) {
      if (grid[i] != 0) continue;

      final count = _bits(masks.candidatesAt(i));
      if (count < bestCount) {
        bestCount = count;
        best = i;
        if (count <= 1) break;
      }
    }
    return best;
  }

  /// Solves [grid], returning null when it has no solution at all.
  static List<int>? solve(List<int> grid) {
    final masks = _masksFor(grid);
    if (masks == null) return null;

    final work = [...grid];

    bool search() {
      final index = _mostConstrained(work, masks);
      if (index == -1) return true;

      var candidates = masks.candidatesAt(index);
      while (candidates != 0) {
        final bit = candidates & -candidates;
        candidates ^= bit;
        final value = bit.bitLength - 1;

        masks.place(index, value);
        work[index] = value;
        if (search()) return true;
        masks.remove(index, value);
        work[index] = 0;
      }
      return false;
    }

    return search() ? work : null;
  }

  /// A complete, valid, randomly generated grid.
  static List<int> _fullGrid(Random rng) {
    final grid = List.filled(cells, 0);
    final masks = _Masks(
      List.filled(size, 0),
      List.filled(size, 0),
      List.filled(size, 0),
    );

    bool fill(int index) {
      if (index == cells) return true;

      final candidates = <int>[];
      var bits = masks.candidatesAt(index);
      while (bits != 0) {
        final bit = bits & -bits;
        bits ^= bit;
        candidates.add(bit.bitLength - 1);
      }
      candidates.shuffle(rng);

      for (final value in candidates) {
        masks.place(index, value);
        grid[index] = value;
        if (fill(index + 1)) return true;
        masks.remove(index, value);
        grid[index] = 0;
      }
      return false;
    }

    fill(0);
    return grid;
  }

  /// A puzzle with exactly one solution.
  static SudokuPuzzle generate(SudokuDifficulty difficulty, [Random? random]) {
    final rng = random ?? Random();
    final solution = _fullGrid(rng);
    final puzzle = [...solution];

    final order = [for (var i = 0; i < cells; i++) i]..shuffle(rng);
    var remaining = cells;

    for (final index in order) {
      if (remaining <= difficulty.givens) break;

      final backup = puzzle[index];
      puzzle[index] = 0;

      // Put it straight back if the grid no longer pins down one answer.
      if (countSolutions(puzzle) != 1) {
        puzzle[index] = backup;
      } else {
        remaining--;
      }
    }

    return SudokuPuzzle(
      givens: puzzle,
      solution: solution,
      difficulty: difficulty,
    );
  }

  /// Cells that clash with another filled cell, for highlighting.
  static Set<int> conflicts(List<int> grid) {
    final bad = <int>{};

    for (var i = 0; i < cells; i++) {
      final value = grid[i];
      if (value == 0) continue;

      for (var j = i + 1; j < cells; j++) {
        if (grid[j] != value) continue;
        if (row(i) == row(j) || col(i) == col(j) || box(i) == box(j)) {
          bad
            ..add(i)
            ..add(j);
        }
      }
    }
    return bad;
  }

  static bool isComplete(List<int> grid) =>
      !grid.contains(0) && conflicts(grid).isEmpty;
}

/// Used-digit bitmasks for each row, column and box.
class _Masks {
  _Masks(this.rows, this.cols, this.boxes);

  final List<int> rows;
  final List<int> cols;
  final List<int> boxes;

  /// The digits still legal at [index], as a bitmask.
  int candidatesAt(int index) {
    final used =
        rows[Sudoku.row(index)] |
        cols[Sudoku.col(index)] |
        boxes[Sudoku.box(index)];
    return Sudoku._all & ~used;
  }

  void place(int index, int value) {
    final bit = 1 << value;
    rows[Sudoku.row(index)] |= bit;
    cols[Sudoku.col(index)] |= bit;
    boxes[Sudoku.box(index)] |= bit;
  }

  void remove(int index, int value) {
    final bit = ~(1 << value);
    rows[Sudoku.row(index)] &= bit;
    cols[Sudoku.col(index)] &= bit;
    boxes[Sudoku.box(index)] &= bit;
  }
}
